from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt

OUT=Path("results")
s=pd.read_csv(OUT/"benchmark_summary.csv")
stats=pd.read_csv(OUT/"paired_statistics.csv")

p=s.pivot(index="dataset",columns="method",values="accuracy_mean")
ax=p.plot(kind="bar",figsize=(15,6)); ax.set_ylabel("Mean 10-fold accuracy"); ax.set_ylim(0,1.05); ax.set_title("APG-AMS and comparator accuracy")
plt.tight_layout(); plt.savefig(OUT/"accuracy_comparison.png",dpi=180); plt.close()

p=s.pivot(index="dataset",columns="method",values="runtime_mean_seconds")
ax=p.plot(kind="bar",figsize=(15,6),logy=True); ax.set_ylabel("Mean fold runtime (s, log scale)"); ax.set_title("End-to-end fold runtime")
plt.tight_layout(); plt.savefig(OUT/"runtime_comparison.png",dpi=180); plt.close()

apg=s[s.method=="APG_AMS"][["dataset","search_reduction_mean_percent"]].sort_values("search_reduction_mean_percent",ascending=False)
ax=apg.plot(x="dataset",y="search_reduction_mean_percent",kind="bar",legend=False,figsize=(13,5)); ax.set_ylabel("Search reduction (%)"); ax.set_title("APG-AMS search reduction")
plt.tight_layout(); plt.savefig(OUT/"search_reduction.png",dpi=180); plt.close()

added=["Ionosphere","Sonar","Banknote","MiceProtein"]
r=s[(s.dataset.isin(added)) & (s.method=="APG_AMS")]
all_apg=s[s.method=="APG_AMS"]
lines=["# Reproducible revision results","","All numerical values are generated by the committed workflow.","",
       f"- Datasets evaluated: {s.dataset.nunique()}",f"- Methods: {', '.join(sorted(s.method.unique()))}",
       f"- Paired dataset-fold units: {int(stats.n_pairs.max())}",
       f"- Mean APG-AMS accuracy across dataset summaries: {all_apg.accuracy_mean.mean():.4f}",
       f"- Mean APG-AMS search reduction across dataset summaries: {all_apg.search_reduction_mean_percent.mean():.2f}%","","## Added real-world datasets"]
for _,x in r.iterrows():
    lines.append(f"- {x.dataset}: n={int(x.n_samples)}, d={int(x.n_features)}, APG accuracy={x.accuracy_mean:.4f}, search reduction={x.search_reduction_mean_percent:.2f}%")
lines += ["","## Paired statistical comparisons","",stats.to_markdown(index=False),"","## Full benchmark summary","",s.to_markdown(index=False)]
(OUT/"RESULTS.md").write_text("\n".join(lines))

response=f'''# Point-by-point response draft\n\n## Reviewer 1\n\n**Response.** We thank the reviewer for this constructive suggestion. We substantially expanded the empirical study. The revised artifact evaluates five methods—Euclidean k-NN, full adaptive p-search, APG-AMS, Neighborhood Components Analysis (NCA), and Large Margin Nearest Neighbor (LMNN)—under common outer 10-fold stratified folds. The evaluation now contains {s.dataset.nunique()} datasets, including four additional real-world datasets (Ionosphere, Sonar, Banknote Authentication, and Mice Protein Expression). We report accuracy, weighted F1, end-to-end runtime, APG-AMS search reduction, and paired statistical tests. These additions directly address the request for deeper comparisons across both datasets and algorithms.\n\n## Reviewer 2\n\n**Response.** We thank the reviewer for identifying this gap. Following the suggested direct-comparison route, we added NCA and LMNN as established supervised metric-learning baselines and evaluated them under the same outer 10-fold protocol as APG-AMS. We also added real-world radar, sonar, image-derived banknote, and protein-expression datasets, including higher-dimensional Sonar and Mice Protein Expression data. The revision preserves the distinction between supervised metric learning and APG-AMS: NCA and LMNN learn transformations, whereas APG-AMS is a screening mechanism that decides when local p-search can be skipped. Accordingly, we compare predictive performance and end-to-end runtime while separately reporting APG-AMS search reduction.\n'''
Path("docs/REVIEWER_RESPONSE_DRAFT.md").write_text(response)
